const inputText = document.getElementById('text-input')
const morseOut = document.getElementById('morse-out')
const morseTranslate = () => {
    let str = inputText.value
    let morseCode = str.toLowerCase().trim()
    .replace(/a/g, '.- ')
    .replace(/b/g, '-... ')
    .replace(/c/g, '-.-. ')
    .replace(/d/g, '-.. ')
    .replace(/e/g, '. ')
    .replace(/f/g, '..-. ')
    .replace(/g/g, '--. ')
    .replace(/h/g, '.... ')
    .replace(/i/g, '.. ')
    .replace(/j/g, '.--- ')
    .replace(/k/g, '-.- ')
    .replace(/l/g, '.-.. ')
    .replace(/m/g, '-- ')
    .replace(/n/g, '-. ')
    .replace(/o/g, '--- ')
    .replace(/p/g, '.--. ')
    .replace(/q/g, '--.- ')
    .replace(/r/g, '.-. ')
    .replace(/s/g, '... ')
    .replace(/t/g, '- ')
    .replace(/u/g, '..- ')
    .replace(/v/g, '...- ')
    .replace(/w/g, '.-- ')
    .replace(/x/g, '-..- ')
    .replace(/y/g, '-.-- ')
    .replace(/z/g, '--.. ')
    .replace(/1/g, '.---- ')
    .replace(/2/g, '..--- ')
    .replace(/3/g, '...-- ')
    .replace(/4/g, '....- ')
    .replace(/5/g, '..... ')
    .replace(/6/g, '-.... ')
    .replace(/7/g, '--... ')
    .replace(/8/g, '---.. ')
    .replace(/9/g, '----. ')
    .replace(/0/g, '----- ')
    .replace(/  /g, '/ ')
    morseOut.textContent = morseCode
    console.log(morseCode)
    console.log(inputText.textContent)
}
inputText.addEventListener('input', morseTranslate)
