# Generated by Django 3.2 on 2021-05-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='logged_user',
            field=models.CharField(max_length=60),
        ),
    ]
