# Generated by Django 3.2 on 2021-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Enter the title here', max_length=300)),
                ('desc', models.TextField(default='Enter the description here')),
                ('summary', models.TextField(default='Enter the summary here')),
                ('price', models.DecimalField(decimal_places=5, max_digits=100)),
            ],
        ),
    ]
